[versions]
agp = "8.1.0-beta03"
org-jetbrains-kotlin-android = "1.8.21"
org-jetbrains-kotlin-coroutines = "1.7.1"
org-jetbrains-kotlin-datetime = "0.4.0"
google-play-services = "4.3.15"
crashlytics = "2.9.6"
compose-bom = "2023.06.00"
firebase-bom = "32.1.1"
firebase-crashlytics = "2.9.2"
firebase-perf = "1.4.2"
compose-icons = "1.4.3"
core-ktx = "1.10.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
face-detection = "16.1.5"
camera = "1.2.3"
datastore = "1.1.0-alpha04"
room = "2.5.1"
decompose = "2.0.0-beta-01"
essenty = "1.1.0"
mvi-kotlin = "3.2.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
timber = "5.0.1"
vico = "1.6.6"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
org-jetbrains-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlin-coroutines" }
org-jetbrains-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "org-jetbrains-kotlin-datetime" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-icons" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
face-detection = { group = "com.google.mlkit", name = "face-detection", version.ref = "face-detection" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ark-mvikotlin-core = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvi-kotlin" }
ark-mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvi-kotlin" }
ark-mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvi-kotlin" }
ark-decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
ark-decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }
ark-essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
google-play-services = { id = "com.google.gms.google-services", version.ref = "google-play-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf" }

[bundles]

